name: Deploy Ecommerce Fullstack App on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            cd ~

            # Install Git if missing
            if ! command -v git &> /dev/null; then
              echo "Installing Git..."
              sudo apt-get update -y
              sudo apt-get install -y git
            fi

            # Install Docker if missing
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker from official repo..."
              sudo apt-get update -y
              sudo apt-get install -y ca-certificates curl gnupg lsb-release

              sudo mkdir -p /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

              sudo apt-get update -y
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io

              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Install Docker Compose if missing
            if ! docker compose version &> /dev/null; then
              echo "Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Clone repo if missing
            if [ ! -d "ecommercefullstack" ]; then
              echo "Project folder not found. Cloning..."
              git clone https://github.com/<your-username>/<your-repo>.git ecommercefullstack
            fi

            cd ecommercefullstack
            git pull origin main

            # Stop old containers
            echo "Stopping old containers..."
            sudo docker compose down || true

            # Build and start new containers
            echo "Building and starting new containers..."
            sudo docker compose up -d --build

            # Show running containers
            echo "Deployment complete. Running containers:"
            sudo docker ps
