name: Deploy Ecommerce Fullstack App on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            cd ~

            # install git, docker, docker-compose if missing
            if ! command -v git &> /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y git
            fi

            if ! command -v docker &> /dev/null; then
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            if ! docker compose version &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # clone repo if missing
            if [ ! -d "ecommercefullstack" ]; then
              git clone https://github.com/<your-username>/<your-repo>.git ecommercefullstack
            fi

            cd ecommercefullstack
            git pull origin main

            # stop old containers
            sudo docker compose down || true

            # build and start
            sudo docker compose up -d --build

            # check running containers
            sudo docker ps
